# Generated by Django 4.1.7 on 2023-02-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormed_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
