# Generated by Django 4.1.7 on 2023-02-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormed_main', '0002_alter_program_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='price',
            name='item',
            field=models.CharField(max_length=150, unique=True, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='program',
            name='results',
            field=models.TextField(blank=True, null=True, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='Title'),
        ),
    ]
