# Generated by Django 4.1.7 on 2023-02-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormed_main', '0003_alter_price_description_alter_price_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='description',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price',
        ),
        migrations.AddField(
            model_name='price',
            name='price_dormed',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cena dla mieszkańców Willi Dorotka i Dormed Medical SPA'),
        ),
        migrations.AddField(
            model_name='price',
            name='price_others',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cena dla klientów z zewnątrz'),
        ),
        migrations.AlterField(
            model_name='price',
            name='item',
            field=models.CharField(max_length=150, unique=True, verbose_name='Rodzaj zabiegu'),
        ),
    ]
