# Generated by Django 4.1.7 on 2023-03-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormed_main', '0005_load_data_from_excel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='price_dormed',
        ),
        migrations.AlterField(
            model_name='price',
            name='price_others',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cena, PLN'),
        ),
    ]
