# Generated by Django 4.1.7 on 2023-03-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormed_main', '0007_program_description_en_program_description_pl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='program',
            name='description_pl',
        ),
        migrations.RemoveField(
            model_name='program',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='program',
            name='results_en',
        ),
        migrations.RemoveField(
            model_name='program',
            name='results_pl',
        ),
        migrations.RemoveField(
            model_name='program',
            name='results_uk',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_uk',
        ),
        migrations.AddField(
            model_name='price',
            name='item_en',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Rodzaj zabiegu'),
        ),
        migrations.AddField(
            model_name='price',
            name='item_pl',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Rodzaj zabiegu'),
        ),
        migrations.AddField(
            model_name='price',
            name='item_uk',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Rodzaj zabiegu'),
        ),
    ]
