# Generated by Django 4.1.7 on 2023-03-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormed_main', '0009_program_description_en_program_description_pl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_uk', models.CharField(max_length=100, null=True)),
                ('title_pl', models.CharField(max_length=100, null=True)),
                ('header', models.CharField(max_length=200)),
                ('header_en', models.CharField(max_length=200, null=True)),
                ('header_uk', models.CharField(max_length=200, null=True)),
                ('header_pl', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('description_pl', models.TextField(null=True)),
                ('features', models.TextField()),
                ('features_en', models.TextField(null=True)),
                ('features_uk', models.TextField(null=True)),
                ('features_pl', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='price',
            name='item_en',
        ),
        migrations.RemoveField(
            model_name='price',
            name='item_pl',
        ),
        migrations.RemoveField(
            model_name='price',
            name='item_uk',
        ),
        migrations.RemoveField(
            model_name='program',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='program',
            name='description_pl',
        ),
        migrations.RemoveField(
            model_name='program',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='program',
            name='results_en',
        ),
        migrations.RemoveField(
            model_name='program',
            name='results_pl',
        ),
        migrations.RemoveField(
            model_name='program',
            name='results_uk',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_uk',
        ),
    ]
