# Generated by Django 4.1.7 on 2023-03-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormed_main', '0011_program_description_en_program_description_pl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='price_others',
        ),
        migrations.AddField(
            model_name='price',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Item price'),
        ),
        migrations.AlterField(
            model_name='hotelnews',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='hotelnews',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='hotelnews',
            name='description_pl',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='hotelnews',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='hotelnews',
            name='features',
            field=models.TextField(verbose_name='Features and what incuded'),
        ),
        migrations.AlterField(
            model_name='hotelnews',
            name='features_en',
            field=models.TextField(null=True, verbose_name='Features and what incuded'),
        ),
        migrations.AlterField(
            model_name='hotelnews',
            name='features_pl',
            field=models.TextField(null=True, verbose_name='Features and what incuded'),
        ),
        migrations.AlterField(
            model_name='hotelnews',
            name='features_uk',
            field=models.TextField(null=True, verbose_name='Features and what incuded'),
        ),
        migrations.AlterField(
            model_name='hotelnews',
            name='header',
            field=models.CharField(max_length=200, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='hotelnews',
            name='header_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='hotelnews',
            name='header_pl',
            field=models.CharField(max_length=200, null=True, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='hotelnews',
            name='header_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='hotelnews',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='hotelnews',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='hotelnews',
            name='title_pl',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='hotelnews',
            name='title_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='price',
            name='item',
            field=models.CharField(max_length=150, unique=True, verbose_name='Item name'),
        ),
    ]
