# Generated by Django 4.1.7 on 2023-03-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormed_main', '0012_remove_price_price_others_price_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='item',
            new_name='position',
        ),
        migrations.AddField(
            model_name='price',
            name='position_en',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Item name'),
        ),
        migrations.AddField(
            model_name='price',
            name='position_pl',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Item name'),
        ),
        migrations.AddField(
            model_name='price',
            name='position_uk',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Item name'),
        ),
    ]
