# Generated by Django 4.1.7 on 2023-03-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormed_main', '0013_rename_item_price_position_price_position_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelnews',
            name='posted_on',
            field=models.DateField(default='2000-01-01', verbose_name='Posted on'),
        ),
    ]
