# Generated by Django 4.1.7 on 2023-03-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormed_main', '0014_hotelnews_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelnews',
            name='posted_on',
            field=models.DateField(default='2000-01-01', verbose_name='Posted on'),
        ),
    ]
