# Generated by Django 4.1.7 on 2023-03-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormed_main', '0015_alter_hotelnews_posted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelnews',
            name='image_left',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/'),
        ),
        migrations.AddField(
            model_name='hotelnews',
            name='image_right',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/'),
        ),
    ]
