# Generated by Django 4.1.7 on 2023-03-29 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormed_main', '0016_hotelnews_image_left_hotelnews_image_right'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelnews',
            options={'verbose_name': 'Hotel News', 'verbose_name_plural': 'Hotel News'},
        ),
    ]
