# Generated by Django 4.1.7 on 2023-03-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormed_main', '0017_alter_hotelnews_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelnews',
            name='image_left',
            field=models.ImageField(blank=True, null=True, upload_to='frontend/static/media/'),
        ),
        migrations.AlterField(
            model_name='hotelnews',
            name='image_right',
            field=models.ImageField(blank=True, null=True, upload_to='frontend/static/media/'),
        ),
    ]
