# Generated by Django 4.1.7 on 2023-03-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormed_main', '0018_alter_hotelnews_image_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelnews',
            name='image_left',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotelnews',
            name='image_right',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
