# Generated by Django 4.1.7 on 2023-05-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormed_main', '0019_alter_hotelnews_image_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='category',
            field=models.CharField(choices=[('KS', 'Kosmetologia'), ('LS', 'Laseroterapia'), ('KT', 'Kosmetyka'), ('ZE', 'Zabiegi Estetyczne'), ('TR', 'Trychologia'), ('PD', 'Podologia')], default='KS', max_length=2),
        ),
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('KS', 'Kosmetologia'), ('LS', 'Laseroterapia'), ('KT', 'Kosmetyka'), ('ZE', 'Zabiegi Estetyczne'), ('TR', 'Trychologia'), ('PD', 'Podologia')], default='KS', max_length=2),
        ),
    ]
