# Generated by Django 4.1.7 on 2023-05-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormed_main', '0020_price_category_program_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='category',
            field=models.CharField(choices=[('KS', 'Kosmetologia'), ('LS', 'Laseroterapia'), ('KT', 'Kosmetyka'), ('ZE', 'Zabiegi Estetyczne'), ('TR', 'Trychologia'), ('PD', 'Podologia'), ('MS', 'Masaże')], default='KS', max_length=2),
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('KS', 'Kosmetologia'), ('LS', 'Laseroterapia'), ('KT', 'Kosmetyka'), ('ZE', 'Zabiegi Estetyczne'), ('TR', 'Trychologia'), ('PD', 'Podologia'), ('MS', 'Masaże')], default='KS', max_length=2),
        ),
    ]
