# fly.toml file generated for dormed on 2023-04-16T11:03:44+02:00

app = "dormed"
primary_region = "waw"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
